"""
Recommendation engine for learning disability interventions.

Provides age-appropriate, severity-aware intervention strategies,
classroom accommodations, and home strategies.
"""
from typing import Dict, List


class RecommendationEngine:
    """Rule-based recommendation system for screening results."""

    SEVERITY_THRESHOLDS = {
        "mild":     (0.40, 0.60),
        "moderate": (0.60, 0.80),
        "severe":   (0.80, 1.00),
    }

    def __init__(self):
        self.db = self._build_database()

    # ── Public ───────────────────────────────────────────────
    def generate(self, prediction: str, probabilities: Dict[str, float],
                 age: int = 8) -> Dict:
        """Return structured recommendations for a screening result."""
        severity = self._severity(prediction, probabilities)
        entry = self.db.get(prediction, self.db["normal"])

        interventions = [
            i for i in entry.get("interventions", [])
            if severity in i.get("severity", [])
            and i["age_range"][0] <= age <= i["age_range"][1]
        ]

        return {
            "severity_level": severity,
            "primary_interventions": interventions,
            "classroom_accommodations": entry.get("classroom_accommodations", []),
            "home_strategies": entry.get("home_strategies", []),
            "disclaimer": (
                "These recommendations are generated by an AI screening tool "
                "and should be reviewed by a qualified specialist before "
                "any clinical or educational decisions are made."
            ),
        }

    # ── Severity ─────────────────────────────────────────────
    def _severity(self, prediction: str, probabilities: Dict[str, float]) -> str:
        if prediction == "normal":
            return "none"
        confidence = probabilities.get(prediction, 0.0)
        for level, (lo, hi) in self.SEVERITY_THRESHOLDS.items():
            if lo <= confidence < hi:
                return level
        return "severe" if confidence >= 0.80 else "mild"

    # ── Intervention database ────────────────────────────────
    @staticmethod
    def _build_database() -> Dict:
        return {
            "dyslexia": {
                "interventions": [
                    {
                        "name": "Phonics-Based Reading Programme",
                        "description": "Structured phonics instruction focusing on sound-letter relationships",
                        "severity": ["mild", "moderate", "severe"],
                        "duration": "3-6 months",
                        "frequency": "4-5 times/week, 30-45 min",
                        "age_range": (6, 12),
                        "resources": ["Orton-Gillingham Approach", "Wilson Reading System"],
                    },
                    {
                        "name": "Multisensory Learning",
                        "description": "Visual, auditory, and kinesthetic methods combined",
                        "severity": ["mild", "moderate", "severe"],
                        "duration": "Ongoing",
                        "frequency": "Daily, 20-30 min",
                        "age_range": (6, 12),
                        "resources": ["Letter tiles", "Sand trays", "Audio books with highlighting"],
                    },
                    {
                        "name": "Assistive Technology",
                        "description": "Text-to-speech and speech-to-text tools",
                        "severity": ["moderate", "severe"],
                        "duration": "Ongoing",
                        "frequency": "As needed",
                        "age_range": (7, 12),
                        "resources": ["Read&Write", "Learning Ally"],
                    },
                    {
                        "name": "One-on-One Specialist Tutoring",
                        "description": "Individualised reading instruction with a trained specialist",
                        "severity": ["moderate", "severe"],
                        "duration": "6-12 months",
                        "frequency": "2-3 times/week, 45-60 min",
                        "age_range": (6, 12),
                        "resources": ["Certified dyslexia specialist"],
                    },
                    {
                        "name": "Reading Comprehension Strategies",
                        "description": "Explicit instruction in comprehension techniques",
                        "severity": ["mild", "moderate"],
                        "duration": "3-6 months",
                        "frequency": "3-4 times/week, 30 min",
                        "age_range": (7, 12),
                        "resources": ["Graphic organisers", "Story maps"],
                    },
                ],
                "classroom_accommodations": [
                    "Extended time on tests (1.5–2x)",
                    "Reduced reading load",
                    "Audio versions of textbooks",
                    "Text-to-speech software access",
                    "Preferential seating near teacher",
                    "Frequent breaks during reading tasks",
                    "Colour-coded materials",
                ],
                "home_strategies": [
                    "Read aloud together daily (15-20 min)",
                    "Use audiobooks for enjoyment",
                    "Practise sight words with flashcards",
                    "Encourage writing through journaling",
                    "Create a quiet, distraction-free study space",
                ],
            },
            "dysgraphia": {
                "interventions": [
                    {
                        "name": "Occupational Therapy",
                        "description": "Fine motor skill development and handwriting practice",
                        "severity": ["mild", "moderate", "severe"],
                        "duration": "3-6 months",
                        "frequency": "2-3 times/week, 30-45 min",
                        "age_range": (6, 12),
                        "resources": ["Handwriting Without Tears"],
                    },
                    {
                        "name": "Structured Handwriting Programme",
                        "description": "Explicit letter formation and spacing instruction",
                        "severity": ["mild", "moderate", "severe"],
                        "duration": "4-8 months",
                        "frequency": "Daily, 15-20 min",
                        "age_range": (6, 12),
                        "resources": ["Size Matters Handwriting Program"],
                    },
                    {
                        "name": "Assistive Writing Technology",
                        "description": "Speech-to-text and word prediction software",
                        "severity": ["moderate", "severe"],
                        "duration": "Ongoing",
                        "frequency": "During writing tasks",
                        "age_range": (7, 12),
                        "resources": ["Google Voice Typing", "Co:Writer"],
                    },
                    {
                        "name": "Grip and Pressure Training",
                        "description": "Proper pencil grip and pressure control exercises",
                        "severity": ["mild", "moderate"],
                        "duration": "2-4 months",
                        "frequency": "Daily, 10-15 min",
                        "age_range": (6, 10),
                        "resources": ["Triangular pencil grips", "Weighted pencils"],
                    },
                    {
                        "name": "Keyboarding Skills",
                        "description": "Touch typing as an alternative to handwriting",
                        "severity": ["moderate", "severe"],
                        "duration": "3-6 months",
                        "frequency": "3-4 times/week, 20-30 min",
                        "age_range": (7, 12),
                        "resources": ["Typing.com", "TypingClub"],
                    },
                ],
                "classroom_accommodations": [
                    "Allow computer/tablet for writing",
                    "Extended time on written assignments",
                    "Reduced writing requirements",
                    "Note-taking assistance",
                    "Accept oral responses",
                    "Graph paper for maths",
                    "Allow lecture recording",
                ],
                "home_strategies": [
                    "Fine motor activities (playdough, beads)",
                    "Encourage drawing and colouring",
                    "Use lined paper with highlighted baseline",
                    "Break writing into smaller chunks",
                    "Praise effort over neatness",
                    "Multisensory writing (sand, shaving cream)",
                ],
            },
            "normal": {
                "interventions": [],
                "classroom_accommodations": [
                    "Continue regular monitoring",
                    "Provide enrichment activities",
                ],
                "home_strategies": [
                    "Maintain regular reading routine",
                    "Encourage creative writing",
                    "Support academic growth",
                ],
            },
        }
