import React from 'react';
import {
  Card, CardContent, Typography, FormControlLabel, Checkbox, Box, Alert,
} from '@mui/material';
import { WarningAmber } from '@mui/icons-material';

export default function ConsentScreen({ accepted, onAccept }) {
  return (
    <Card elevation={2}>
      <CardContent>
        <Typography variant="h5" gutterBottom>
          Consent &amp; Disclaimer
        </Typography>

        <Alert severity="info" icon={<WarningAmber />} sx={{ mb: 3 }}>
          Please read the following carefully before proceeding.
        </Alert>

        <Typography variant="body1" paragraph>
          This Learning Disability Screening System is an AI-assisted tool designed to
          identify <strong>potential risk indicators</strong> for dyslexia and dysgraphia
          in children aged 6–12. It analyses handwriting samples and speech recordings
          to produce a screening result with recommendations.
        </Typography>

        <Typography variant="body1" paragraph>
          <strong>Important:</strong>
        </Typography>

        <Box component="ul" sx={{ pl: 3, mb: 2 }}>
          <li>This tool does <strong>not</strong> provide a medical or clinical diagnosis.</li>
          <li>Results should be reviewed by a qualified professional (educational psychologist, speech therapist, or paediatrician).</li>
          <li>No personally identifiable data is transmitted to external servers beyond the speech-to-text API used for transcription.</li>
          <li>Uploaded images and audio are processed temporarily and deleted immediately after analysis.</li>
          <li>All recommendations are generated by an AI model and may not be suitable for every child.</li>
        </Box>

        <Typography variant="body1" paragraph>
          By proceeding, you confirm that you have read and understood the above, and that
          you consent to use this tool for screening purposes only.
        </Typography>

        <FormControlLabel
          control={
            <Checkbox
              checked={accepted}
              onChange={(e) => onAccept(e.target.checked)}
              color="primary"
            />
          }
          label="I have read and accept the above disclaimer and consent to proceed."
        />
      </CardContent>
    </Card>
  );
}
